server:
  port: 8082

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/products-db
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
