name: Build and Deploy Microservices

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          for service in user-service product-service order-service api-gateway discovery-service kafka-service config-server; do
            docker build -t ${{ secrets.DOCKER_USERNAME }}/${service}:latest ./$service
            docker push ${{ secrets.DOCKER_USERNAME }}/${service}:latest
          done

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f user-service/deployment.yaml
          kubectl apply -f product-service/deployment.yaml
          kubectl apply -f order-service/deployment.yaml
          kubectl apply -f api-gateway/deployment.yaml
          kubectl apply -f discovery-service/deployment.yaml
          kubectl apply -f kafka-service/deployment.yaml
          kubectl apply -f config-server/deployment.yaml
